#!/bin/bash

# Needed by circleci local build tool
exec < /dev/tty

echo "##### Running pre-commit hook #####"
root="$(pwd)"

# Run clang-format on all staged CXX source files
bash "${root}/.githooks/clangformat.sh"

# Run cmake-format on cmake lists files
bash "${root}/.githooks/cmakeformat.sh"

# Referred:  https://circleci.com/blog/circleci-hacks-validate-circleci-config-on-every-commit-with-a-git-hook/
# Validates circleci config file
if ! msg=$(circleci config validate -c .circleci/config.yml); then
	echo "Failed circleci validation"
	exit 1
else
	echo $msg
fi
