version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    enviroment:
          CXX: "clang++-8"
          CMAKE_BUILD_TYPE: "Release"
          LD_LIBRARY_PATH: "/root/project/simulator/lib:${LD_LIBRARY_PATH}"
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
            apt update
            apt install -y --no-install-recommends build-essential clang-8 clang-format-8 llvm-8 llvm-8-dev llvm-8-runtime
            wget "https://cmake.org/files/v3.15/cmake-3.15.4-Linux-x86_64.tar.gz" --no-check-certificate
            wget "https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz" --no-check-certificate
            tar xf cmake-3.15.4-Linux-x86_64.tar.gz
            tar xf boost_1_68_0.tar.gz
            cp -r cmake-3.15.4-Linux-x86_64/bin/* /usr/local/bin
            cp -r cmake-3.15.4-Linux-x86_64/share/* /usr/local/share
            cp -r boost_1_68_0/* /usr/local/share/boost/*
            mkdir simulator build
      - run:
          name: Run CMake
          working_directory: /root/project/build
          command: |
            cmake .. -DCMAKE_INSTALL_PREFIX=/root/project/simulator -DCMAKE_CXX_COMPILER=clang++-8 -DBOOST_ROOT=/usr/local/share/boost
      - run:
          name: Run Make
          working_directory: /root/project/build
          command: |
            make install -j
      - run:
          name: Run Tests
          working_directory: /root/project/simulator/bin
          command: ./tests
      - run:
          name: Run Linter Tests
          working_directory: /root/project/.circleci
          command: |
            ./linter-check.sh
      - run:
          name: Setup Doxygen and Sphinx
          working_directory: /root
          command: |
            apt update
            apt install -y doxygen python3-pip
            python3 -m pip install sphinx_rtd_theme breathe
      - run:
          name: Build Doxygen documentation.
          working_directory: /root/project
          command: |
            doxygen && cd docs/ && make html && cd ../
